### ISSUE TITLE
[question] realworld example with a cloud resource

### ISSUE THREAD

**Issue by codebydant** [NikolaLohinski/terraform-provider-jinja#13]
Hi @NikolaLohinski 

Thanks for this wonderful tool.

Would be great an example of how to use this tool with a cloud provider since I am kind lost with the provided example.

My idea is to use this tool to replicate the same terraform module with different configuration files (context.yaml).

**Comment by NikolaLohinski** [comment]
Hi @dtcMLOps 

> Thanks for this wonderful tool.

You are most welcome :smile: 

> an example of how to use this tool with a cloud provider 

I am not sure I follow. What are your trying to achieve exactly? Would you mind sharing a more precise example about what you are trying to do ?

This provider is in memory only. It does not interact with any remote API. It basically takes a text input and writes a text output to the `result` field of the `template` data source.

You won't be able to generate `terraform` files with this provider in the same runtime as you would apply them if that is what you are trying to do.

**Comment by codebydant** [comment]
Hi @NikolaLohinski 

Thanks for a such quick response. So, let me explain my use case:

I have a terraform module.
I want to generate multiple resources of the same module using different configuration files.
I understand jinja takes a template and merges the configuration files into the template.

So, my idea is to take this approach to replicate multiple resources of the same type using different configs
![image](https://github.com/NikolaLohinski/terraform-provider-jinja/assets/115469901/b571b14e-efca-404e-bdc7-3d8b78de11e1)


The content of the `template.j2` is similar to this one:

```j2
From context:
module {{ standard_name }}-{{ mycountry }}-module {
  # Import Databricks job module
  source = {{ source }}

  run_as        = {{ run_as }}
  workflow_name = "{{ standard_name }}-{{ mycountry }}-module-{{ env }}"
  tags = {{ tags }}
  git_url      = {{ git_url }}
  git_branch   = "main"
  git_provider = {{ git_provider }}
  email_notifications = {{ email_notifications }}
  enable_cluster_permissions = {{ enable_cluster_permissions | lower }}
  access_control_users = {{ access_control_users }}
  access_control_groups = {{ access_control_groups }}

...

}
```

and an example of a `config.yml` file is:

```yml
---
source: "mymodule?ref=v1.2.0"

mycountry : "MX"
standard_name: myworkfow
tags:
git_url: "myrepo"
git_provider: "gitHub"
email_notifications:
  on_start:
  on_failure:
    - myemail
  on_success:
  no_alert_for_skipped_runs: false
  alert_on_last_attempt: false
enable_cluster_permissions: true
access_control_users:
  - user_name: myemail
    permission_level: IS_OWNER

access_control_groups:
  - group_name: mygroup
    permission_level: CAN_VIEW

...
```

I want to be able to replicate the module with differen configs. Do you think this can be achieved with the jinja provider?
