### ISSUE TITLE
dict support

### ISSUE THREAD

**Issue by yannickvr** [NikolaLohinski/terraform-provider-jinja#2]
I'm trying to use this provider with some existing Jinja2 templates.

**Relevant template:**
```
{% for parameter_name, parameter_value in ParameterGroupConfig.items() %}
        {{parameter_name}}: {{ parameter_value }}
{% endfor %}
```

**Relevant input:**

```
ParameterGroupConfig:
  audit_logs: "enabled"
  change_stream_log_retention_duration: "10800"
  profiler: "enabled"
  profiler_sampling_rate: "1.0"
  profiler_threshold_ms: "100"
  tls: "enabled"
  ttl_monitor: "enabled"
```

Result is error stating ForStmt cannot be parsed. Is this supported with different input?
